import {BsFacebook,BsYoutube} from "react-icons/bs"
// import {ImInstagram} from "react-icons/im"
// import {FaSquareInstagram} from "react-icons/fa"
import {AiOutlineTwitter,AiFillStar,AiFillInstagram} from "react-icons/ai"
import {BiLogoFacebookSquare} from "react-icons/bi";

import {Mencasual1,Mencasual2,Mencasual3,Mencasual4,Mencasual5,Mencasual6,Mencasual7,Mencasual8,Mencasual9,
MenHalfsleeves1,MenHalfsleeves2,MenHalfsleeves3,MenHalfsleeves4,MenHalfsleeves5,MenHalfsleeves6,MenHalfsleeves7,MenHalfsleeves8,Menpolo1,Menpolo2,Menpolo3,Menpolo4,Menpolo5,
Menroadster1,Menroadster2,Menroadster3,Menroadster4, Menroadster5,Menroadster6,Menroadster7,Menroadster8,Menroadster9,Menroadster10,Menroadster11, Menroadster12, Menroadster13,
Mensleevless1,Mensleevless2,Mensleevless3,Mensleevless4,
Mentshirt1,Mentshirt2,Mentshirt3,Mentshirt4,Mentshirt5,Mentshirt6,Mentshirt7,Mentshirt8,Mentshirt9,Mentshirt10,Mentshirt11,
// women
  Womencasual1,Womencasual2,Womencasual3,Womencasual4,Womencasual5,Womencasual6,Womencasual7, Womencasual8,
    Womenhalfsleeves1,Womenhalfsleeves2,Womenhalfsleeves3,Womenhalfsleeves4,Womenhalfsleeves5,Womenhalfsleeves6,
    Womenpolo1,  Womenpolo2,  Womenpolo3,  Womenpolo4,  Womenpolo5,  Womenpolo6,
   Womenroadster1,   Womenroadster2,   Womenroadster3,   Womenroadster4,
   Womensleevless1,   Womensleevless2,   Womensleevless3,
  Womentshirt1,  Womentshirt2,  Womentshirt3,  Womentshirt4,  Womentshirt5,  Womentshirt6,  Womentshirt7,
   
} from "../Images/index" 

export const FooterCol1 = [
  {
    title: "Online Shopping",
    links: [
      {
        id:"men",
        name: "Men",
      },
      {
        id:"women",
        name: "Women",
      },
      {
        id:"kids",
        name: "Kids",
      },
      {
        id:"homeandliving",
        name: "Home & Living",
      },
      {
        id:"beauty",
        name: "Beauty",
      },
      {
        id:"giftcards",
        name: "Gift Cards",
      },
      {
        id:"myntraInsider",
        name: "Myntra Insider",
      },
    ],
  },
]

export const FooterCol2 = [
  {
    title: "Customer polices",
    links: [
      {
        id:"contactus",
        name: "Contact Us",
      },
      {
        id:"faq",
        name: "FAQ",
      },
      {
        id:"t&c",
        name: "T&C",
      },
      {
        id:"Termsofuse",
        name: "Terms Of Use",
      },
      {
        id:"trackorders",
        name: "Track Orders",
      },
      {
        id:"shipping",
        name: "Shipping",
      },
      {
        id:"cancellation",
        name: "Cancellation",
      },
      {
        id:"returns",
        name: "Returns",
      },
      {
        id:"privacypolicy",
        name: "Privacy policy",
      },
      {
        id:"grievance Officer",
        name: "Grievance Officer",
      },
    ],
  },
]

export const FooterCol3b = [
  {
    title: "KEEP IN TOUCH",
    links: [
      {
        id:"facebook",
        icon:BiLogoFacebookSquare
      },
      {
        id:"instagram",
        icon:AiFillInstagram
      },
      
      {
        id:"youtube",
        icon:BsYoutube
      },
      
      {
        id:"twitter",
        icon:AiOutlineTwitter
        
      },
    ],
  },
]

export const FooterRow2 = [
  {
    title: "Useful Links",
    links: [
      {
        id:"blog",
        name: "Blog",
      },
      {
        id:"Career",
        name: "Career",
      },
      {
        id:"Site Map",
        name: "Site Map",
      },
      {
        id:"corporateinformation",
        name: "Corporate Information",
      },
      {
        id:"Whitehat",
        name: "Whitehat",
      },
    ],
  },
]

export const FooterRow3 = [
  {
    title: "Popular Searches",
    links:[
      "Shorts","Jeans","Party Wear", "Jackets","Sherwani", "Jumpsuits","Men Shirt","Track pants", "Ripped Jeans", "coats","Men Tshirts","Capris","Biker Jacket","Shrugs","Tshirts","Men Kurtas","Kurta Pyjama","Sweaters","Leather Jackets","Kurta","Tracksuits","Sherwanis","Wedding Dresses For Men" ,"Bomber Jackets","Men Shirts","Distressed Jeans","Streetwear","Jerseys","Cricket Tshirts","Football Jerseys","Pants","Rain Jackets","Chinos","Cargo Pants","Men Innerwear","Boxers","Vests","Men Trunks","Thongs","Sportswear","Gym Wear","Sweatshirts","Men T Shirts","Men Trousers","Men Jackets","Men Sweaters","Men Shrugs","Men Jeans","Men Track Pants","Myntra Fashion Show" 
    ]
  },
];

export const productImages = [
  {
    id: 1,
    gender:"men",
    category:"casual",
    mainImage: Mencasual1,
    otherImages: [Mencasual1, Mencasual2, Mencasual3, Mencasual4, Mencasual5, Mencasual6,],
    rating:"4.2",
    star:AiFillStar,
    Knumbering:"4.5k",
    title:"Men Casual Shirt",
    para:"Men Slim Fit Casual Sustainable Shirt",
    RealPrice:" 2099",
    DiscountPrice:" 776",
    size:"45",
    dropdownList:"Recommended",
  },
  {
    id: 2,
    gender:"men",
    category:"casual",
    mainImage: Mencasual7,
    otherImages: [Mencasual7, Mencasual8, Mencasual9],
    rating:"4.4",
    star:AiFillStar,
    Knumbering:"6.5k",
    title:"Men Casual Shirt",
    para:"Men Slim Fit Casual Sustainable Shirt",
    RealPrice:" 5099",
    DiscountPrice:" 2776",
    size:"42",
    dropdownList:"Popularity",
  },
  {
    id: 3,
    gender:"men",
    category:"halfsleev",
    mainImage: MenHalfsleeves1,
    otherImages: [MenHalfsleeves1,MenHalfsleeves2,MenHalfsleeves3,MenHalfsleeves4,],
    rating:"4.1",
    star:AiFillStar,
    Knumbering:"2.5k",
    title:"Men Halfsleeves Shirt",
    para:"Men Slim Fit Halfsleeves Sustainable Shirt",
    RealPrice:" 32099",
    DiscountPrice:" 25776",
    size:"44",
    dropdownList:"What's New",
  },
  {
    id: 4,
    gender:"men",
    category:"halfsleev",
    mainImage: MenHalfsleeves5,
    otherImages: [MenHalfsleeves5,MenHalfsleeves6,MenHalfsleeves7,MenHalfsleeves8],
    rating:"4.2",
    star:AiFillStar,
    Knumbering:"8.5k",
    title:"Men Halfsleeves Shirt",
    para:"Men Slim Fit Halfsleeves Sustainable Shirt",
    RealPrice:" 20999",
    DiscountPrice:" 31776",
    size:"40",
    dropdownList:"",
  },
  {
    id: 5,
    gender:"men",
    category:"polo",
    mainImage: Menpolo1,
    otherImages: [Menpolo1,Menpolo2,Menpolo3,Menpolo4,Menpolo5,],
    rating:"4.0",
    star:AiFillStar,
    Knumbering:"4.5k",
    title:"Men polo Shirt",
    para:"Men Slim Fit polo Sustainable Shirt",
    RealPrice:" 12099",
    DiscountPrice:" 2776",
    size:"30",
    dropdownList:"Better Discount",
  },
  {
    id: 6,
    gender:"men",
    category:"roadster",
    mainImage: Menroadster1,
    otherImages: [Menroadster1,Menroadster2,Menroadster3,Menroadster4, Menroadster5,],
     rating:"3.9",
    star:AiFillStar,
    Knumbering:"8.5k",
    title:"Men Roadster Shirt",
    para:"Men Slim Fit Roadster Sustainable Shirt",
    RealPrice:" 2090",
    DiscountPrice:" 276",
    size:"35",
    dropdownList:"Better Discount",
  },
  {
    id: 7,
    gender:"men",
    category:"roadster",
    mainImage: Menroadster6,
    otherImages: [Menroadster6,Menroadster7,Menroadster8,Menroadster9,],
     rating:"3.2",
    star:AiFillStar,
    Knumbering:"6.5k",
    title:"Men Roadster Shirt",
    para:"Men Slim Fit Roadster Sustainable Shirt",
    RealPrice:" 12090",
    DiscountPrice:" 1276",
    size:"42",
    dropdownList:"Better Discount",
    
  },
  {
    id: 8,
    gender:"men",
    category:"roadster",
    mainImage: Menroadster10,
    otherImages: [Menroadster10,Menroadster11, Menroadster12, Menroadster13,],
     rating:"4.2",
    star:AiFillStar,
    Knumbering:"7.5k",
    title:"Men Roadster Shirt",
    para:"Men Slim Fit Roadster Sustainable Shirt",
    RealPrice:" 21090",
    DiscountPrice:" 2276",
    size:"42",
    dropdownList:"Better Discount",
    
  },
  {
    id: 9,
    gender:"men",
    category:"sleevless",
    mainImage: Mensleevless1,
    otherImages: [Mensleevless1,Mensleevless2,Mensleevless3,Mensleevless4,],
     rating:"4.3",
    star:AiFillStar,
    Knumbering:"8.5k",
    title:"Men Sleevless Shirt",
    para:"Men Slim Fit sleevless Sustainable Shirt",
    RealPrice:" 2090",
    DiscountPrice:" 1276",
    size:"47",
    dropdownList:"Recommended",
    
  },
  {
    id: 10,
    gender:"men",
    category:"tshirt",
    mainImage: Mentshirt1,
    otherImages: [Mentshirt1,Mentshirt2,Mentshirt3,Mentshirt4,Mentshirt5,],
     rating:"3.7",
    star:AiFillStar,
    Knumbering:"3.5k",
    title:"Men Tshirt ",
    para:"Men Slim Fit Tshirt ",
    RealPrice:" 2090",
    DiscountPrice:" 876",
    size:"39",
    dropdownList:" What's New",
    
  },
  {
    id: 11,
    gender:"men",
    category:"tshirt",
    mainImage: Mentshirt6,
    otherImages: [Mentshirt6,Mentshirt7,Mentshirt8,],
     rating:"4.0",
    star:AiFillStar,
    Knumbering:"5.5k",
    title:"Men Tshirt ",
    para:"Men Slim Fit Tshirt ",
    RealPrice:" 6090",
    DiscountPrice:" 976",
    size:"23",
    dropdownList:"Popularity",
  },
  {
    id: 12,
    gender:"men",
    category:"tshirt",
    mainImage: Mentshirt9,
    otherImages: [Mentshirt9,Mentshirt10,Mentshirt11,],
     rating:"4.2",
    star:AiFillStar,
    Knumbering:"6.5k",
    title:"Men Tshirt ",
    para:"Men Slim Fit Tshirt ",
    RealPrice:" 6090",
    DiscountPrice:" 2276",
    size:"22",
    dropdownList:"Popularity",
  },
  // women
  {
    id: 13,
    gender:"women",
    category:"casual",
    mainImage: Womencasual1,
    otherImages: [Womencasual1,Womencasual2,Womencasual3,Womencasual4,],
     rating:"4.1",
    star:AiFillStar,
    Knumbering:"7.5k",
    title:"Women Casual Shirt",
    para:"Women Slim Fit Women Casual Sustainable Shirt",
    RealPrice:" 7090",
    DiscountPrice:" 3276",
    size:"43",
    dropdownList:"Popularity",
  },
  {
    id: 14,
    gender:"women",
    category:"casual",
    mainImage: Womencasual5,
    otherImages: [Womencasual5,Womencasual6,Womencasual7, Womencasual8,],
     rating:"4.3",
    star:AiFillStar,
    Knumbering:"3.5k",
    title:"Women Casual Shirt",
    para:"Women Slim Fit Roadster Sustainable Shirt",
    RealPrice:" 2090",
    DiscountPrice:" 476",
    size:"36",
    dropdownList:"Better Discount",
  },
  {
    id: 15,
    gender:"women",
    category:"halfsleev",
    mainImage: Womenhalfsleeves1,
    otherImages: [Womenhalfsleeves1,Womenhalfsleeves2,Womenhalfsleeves3,],
     rating:"3.8",
    star:AiFillStar,
    Knumbering:"3.5k",
    title:"Women Halfsleeves Shirt",
    para:"Women Slim Fit Women Halfsleeves Sustainable Shirt",
    RealPrice:" 2090",
    DiscountPrice:" 576",
    size:"24",
    dropdownList:"Recommended",
  },
  {
    id: 16,
    gender:"women",
    category:"halfsleev",
    mainImage: Womenhalfsleeves4,
    otherImages: [Womenhalfsleeves4,Womenhalfsleeves5,Womenhalfsleeves6,],
     rating:"4.2",
    star:AiFillStar,
    Knumbering:"6.5k",
    title:"Women Halfsleeves Shirt",
    para:"Women Slim Fit Women Halfsleeves Sustainable Shirt",
    RealPrice:" 2090",
    DiscountPrice:" 1276",
    size:"19",
    dropdownList:"What's New",
  },
  {
    id: 17,
    gender:"women",
    category:"polo",
    mainImage:Womenpolo1,
    otherImages: [Womenpolo1,  Womenpolo2,],
     rating:"4.0",
    star:AiFillStar,
    Knumbering:"8.5k",
    title:"Women Polo Shirt",
    para:"Women Slim Fit Women Polo Sustainable Shirt",
    RealPrice:" 4090",
    DiscountPrice:" 2076",
    size:"41",
    dropdownList:"Better Discount",
  },
  {
    id: 18,
    gender:"women",
    category:"polo",
    mainImage:Womenpolo3,
    otherImages: [Womenpolo3,  Womenpolo4,  Womenpolo5,  Womenpolo6,],
     rating:"4.3",
    star:AiFillStar,
    Knumbering:"9.5k",
    title:"Women Polo Shirt",
    para:"Women Slim Fit  Sustainable Shirt",
    RealPrice:" 2090",
    DiscountPrice:" 576",
    size:"40",
    dropdownList:"Popularity",
  },
  {
    id: 19,
    gender:"women",
    category:"roadster",
    mainImage:Womenroadster1,
    otherImages: [Womenroadster1,   Womenroadster2,   Womenroadster3,   Womenroadster4,],
     rating:"4.1",
    star:AiFillStar,
    Knumbering:"4.5k",
    title:"Women Roadster Shirt",
    para:"Women Slim Fit Roadster Sustainable Shirt",
    RealPrice:" 62090",
    DiscountPrice:" 40276",
    size:"34",
    dropdownList:"What's New",
  },
  {
    id: 20,
    gender:"women",
    category:"sleevless",
    mainImage:Womensleevless1,
    otherImages: [Womensleevless1,   Womensleevless2,   Womensleevless3,],
     rating:"4.2",
    star:AiFillStar,
    Knumbering:"5.5k",
    title:"Women Sleevless Shirt",
    para:"Women Slim Fit Sleevless Sustainable Shirt",
    RealPrice:" 32090",
    DiscountPrice:" 25276",
    size:"39",
    dropdownList:"What's New",
  },
  {
    id: 21,
    gender:"women",
    category:"tshirt",
    mainImage:Womentshirt1,
    otherImages: [Womentshirt1,  Womentshirt2,  Womentshirt3,  Womentshirt4, ],
     rating:"4.0",
    star:AiFillStar,
    Knumbering:"8.5k",
    title:"Women TShirt",
    para:"Women Slim Fit TShirt",
    RealPrice:" 2090",
    DiscountPrice:" 876",
    size:"37",
    dropdownList:"Popularity",
  },
  {
    id: 22,
    gender:"women",
    category:"tshirt",
    mainImage:Womentshirt5,
    otherImages: [Womentshirt5,  Womentshirt6,  Womentshirt7,],
     rating:"4.2",
    star:AiFillStar,
    Knumbering:"9.5k",
    title:"Women TShirt",
    para:"Women Slim Fit TShirt",
    RealPrice:" 8090",
    DiscountPrice:" 6276",
    size:"45",
    dropdownList:"Recommended",
  },

];
